### ISSUE TITLE
Add this library to vcpkg

### ISSUE THREAD

**Issue by kelteseth** [danvratil/qcoro#185]
Hi all,
Thanks for this wonderful library. It would be awesome if we could add this to [vcpkg](https://github.com/microsoft/vcpkg), so that I can have all of my dependencies installed in one command 😁

**Comment by danvratil** [comment]
Great idea :)

I submitted PRs to vcpkg:
* qcoro-qt5: https://github.com/microsoft/vcpkg/pull/33272/
* qcoro-qt6: https://github.com/microsoft/vcpkg/pull/33273

For now without OSX support, because the release build in the CI crashes the Apple Clang compiler, but [I'll look into](https://github.com/danvratil/qcoro/issues/186) later.
