### ISSUE TITLE
Early co_returns do not resume the caller

### ISSUE THREAD

**Issue by rgriebl** [danvratil/qcoro#24]
Maybe I'm not understanding correctly how coroutines work, but I think the following example should work for both cases: returning early and awaited from `testReturn`.
What I'm seeing (gcc 11 and MSVC 2019) is that `testImmediate` just hangs and never returns from its `co_await`
```
static QCoro::Task<bool> testReturn(bool immediate)
{
    qWarning() << "Running testReturn(immediate:" << immediate << ")";
    if (immediate) {
        co_return true;
    } else {
        QTimer t;
        t.start(100);
        co_await(t);
        co_return true;
    }
}

static QCoro::Task<> testImmediate()
{
    qWarning() << "Starting Immediate...";
    bool b = co_await testReturn(true);
    qWarning() << "Immediate result:" << b;
}

static QCoro::Task<> testDelayed()
{
    qWarning() << "Starting Delayed...";
    bool b = co_await testReturn(false);
    qWarning() << "Delayed result:" << b;
}

int main(int argc, char **argv)
{
    QCoreApplication a(argc, argv);
    QMetaObject::invokeMethod(qApp, []{ testImmediate(); }, Qt::QueuedConnection);
    QMetaObject::invokeMethod(qApp, []{ testDelayed(); }, Qt::QueuedConnection);
    return a.exec();
}
```

Output:
```
Starting Immediate...
Running testReturn(immediate: true )
Starting Delayed...
Running testReturn(immediate: false )
Delayed result: true
```

**Comment by danvratil** [comment]
Indeed, this should work as you described. Thanks for the nice reproducer.

**Comment by rgriebl** [comment]
Is there anything I could help with debugging? I'm just starting out with co-routines, so I'm still a bit lost in all the template magic, but maybe you have an idea/hint what may go wrong here?

**Comment by danvratil** [comment]
Hi, sorry for not fixing this yet, I'm a bit busy with work :( The problem is that the fact that the coroutine has finished synchronously doesn't propagate to the Task<> that is returned to the caller, so when you `co_await` that Task, it goes to a regular suspend, expecting that it will be awoken eventually when the coroutine finishes - which is where things break, because the coroutine has already finished.

The fix here is to check for the state of the Task before suspending it...

**Comment by rgriebl** [comment]
Hi, no big deal. I now tried to fix this myself, but I can't get it to work 100%:
 * Thanks to the logic around the `mResumeAwaiter` atomic, it should work already fine in theory. 
 * The problem is the `finishedCoroutine.destroy()` call in `TaskFinalSuspend`, because this destroys the result value too early in the immediate co_return case.
 * If I comment out that `destroy()` call then the program works as expected, but this creates a memory leak (at least I think it does ;) )
 * Looking at cppcoro, I see that they are destroying the co-routine in `~Task`, but if I do the same, then the second case (the delayed return) hangs forever.

Any ideas?

**Comment by danvratil** [comment]
Your investigation is correct and you are heading in the right direction.There are two cases that main need to be handled:

1) When the `Task<>` returned from coroutine is ignored by the caller (this happens when your coroutine is invoked from the Qt event loop)
2) When the `Task<>` returned from coroutine is not ignored by the caller (i.e. it's `co_await`ed y the caller of the coroutine)

I think the right approach that I'm pursuing now, is to indeed destroy the coroutine from `~Task`, but only if the coroutine is finished when the `Task` is destroyed. If the coroutine is only suspended when the Task is destroyed (which happens in case 1.), then the destruction of the coroutine must be left to the `TaskFinalSuspend` (which is basically a kind of coroutine "self-destruct".
