### ISSUE TITLE
Doesn't work on Debian 11?

### ISSUE THREAD

**Issue by krab** [danvratil/qcoro#32]
Debian 11: `gcc version 10.2.1`
Build is fine after lowering cmake version requirement to 3.18 and removing `include(HasCompatibleStlAbi)` (doesn't work under 3.18 i think).

But in QtCreator in getting compile error on code:
```
const QDBusReply<UDisks2::Introspection> reply = co_await udisks2_iface.asyncCall(QStringLiteral("GetManagedObjects"));

error: unable to find the promise type for this coroutine
```

QtCreator doesn't like `co_await` keyword https://i.imgur.com/fUR5LRQ.png `set(CMAKE_CXX_STANDARD 20)` enabled

**Comment by krab** [comment]
Actually nvm. Correct `QCoro::Task<` builds in Debian 11. But QtCreator show erros due to clang code model?

**Comment by danvratil** [comment]
The problem with QtCreator might be, that it's using LLVM/clang to provide code inspection/completion, but at the same time you are likely targeting GCC and libstdc++. Since LLVM is used for code completion, it "enables" some clang-detection macros in the code that resolve `QCORO_STD` macro to `std::experimental` (since in clang, that's where coroutines are implemented). You are, however, targeting GCC and libstdc++, where coroutines are in `std` namespace, so LLVM "rightfully" complains, that `std::experimental::coroutine_handle` does not exist in libstdc++.

This is probably related to #22 and has the same fix: get rid of the QCORO_STD macro and provide a custom standard-compliant implementation for clang rather).

Regarding the build error, I would probably need a bit more to go on (either the full error message, and ideally some small sample of your code). Is the function that you are calling this code from also a coroutine (does it have QCoro::Task<>` return type)?

**Comment by krab** [comment]
> does it have QCoro::Task<>` return type)?

Yep it fixed now after fixing Task. So QtCreator visual errors simply not fixable until clang moves coroutines into std.
