### ISSUE TITLE
Build and install Qt 5 and Qt 6 version in a single pass

### ISSUE THREAD

**Issue by xvitaly** [danvratil/qcoro#42]
Build and install Qt 5 and Qt 6 version in a single pass. It will help GNU/Linux package maintainers.

Now we need to perform two separate builds.

**Comment by krop** [comment]
As a package maintainer, I'd prefer things to remain like they are.

**Comment by danvratil** [comment]
Building both versions with a single pass would be more trouble than it's worth, to be honest, since you need to make sure everything happens twice, no files overlap and everything is properly isolated. At that point, it's easier to just have to build dirs and run cmake in both separately. 

I'm not going to implement this, sorry.
