### ISSUE TITLE
apple-clang support

### ISSUE THREAD

**Issue by ericLemanissier** [danvratil/qcoro#43]
Hello, I'm currently trying to make a conan package for qcoro on https://github.com/conan-io/conan-center-index/pull/8870, 
but the build on apple-clang 12 fails with 
```
/Users/jenkins/w/BuildSingleReference@3/.conan/data/qcoro/0.4.0/_/_/build/77eb698670f46be85ef6b72390c811f44c09c9aa/source_subfolder/qcoro/concepts_p.h:9:10: fatal error: 'concepts' file not found
#include <concepts>
```
More details on https://c3i.jfrog.io/c3i/misc/logs/pr/8870/5-configs/macos-clang/qcoro/0.4.0//77eb698670f46be85ef6b72390c811f44c09c9aa-build.txt

is apple-clang supported ? If yes, starting with which version ?

Thanks !

**Comment by ysc3839** [comment]
According to https://en.cppreference.com/w/cpp/compiler_support/20, I think it's not supported.

**Comment by ericLemanissier** [comment]
ok. These two commits lead me to think otherwise; https://github.com/danvratil/qcoro/commit/6629c7d8fdb8667e24735c794edb500a46549964 https://github.com/danvratil/qcoro/commit/b6787b78e680f5dc161cd5c36bac002e0f18a397

**Comment by danvratil** [comment]
Hmm, the MacOS support may have been added before I introduced the `<concepts>` header dependency and thus broken the build, since I'm not testing on MacOS regularily...I really have to add MacOS CI :-)

As far as I know, the concepts implementation in libc++ is rather incomplete, although on Linux at least I do have the header. I'll try to fix it, I'd like to have MacOS fully supported!

**Comment by ericLemanissier** [comment]
loosely linked to this issue, but qcoro has been approved in conan-center : https://conan.io/center/qcoro

**Comment by danvratil** [comment]
Thanks a lot for submitting QCoro to Conan, much appreciated!

Sadly, I did not yet get around to undust my Macbook and get it working there again :(

**Comment by danvratil** [comment]
I was only able to test with apple-clang 13.0.0 (on Big Sur) and since commit b4abc58 the build works and tests pass.

It's possible that older versions of apple-clang won't work due to lack of C++20 support. But at least we now have MacOS CI, so it shouldn't break again :-)

Is it possible to specify minimum supported version of MacOS/XCode (not sure which one defines the  version of apple-clang) on conan.io?
