### ISSUE TITLE
Rename task.h to qcorotask.h

### ISSUE THREAD

**Issue by jmiturasolutions** [danvratil/qcoro#70]
All headers in QCoro have QCoro prefix, except for Task. There can be different libraries (private or public) which also use this term. It would be more readable and less conflicting to rename it to QCoroTask.

Additionally QCoroTaskFwd could be introduced to reduce code duplication when forward declaring coroutines in headers:
```
namespace QCoro {
template<typename T>
class Task;
}
```

**Comment by danvratil** [comment]
You should use `#include <QCoro/Task>` (or `#include <qcoro/task.h>` ) rather than just `#include <task.h>` (which indeed could clash with "task.h" from current project or other library).

I agree that `QCoroTask` would be a more consistent and clearer name. But just renaming the file would break all existing code, so I'll have to keep the old header around with some deprecation warning for a couple of releases before removing it completely.

**Comment by jmiturasolutions** [comment]
If I include Task.h, which is a private project header, linker uses qcoro/task.h instead (private Task.h is in separate dll). This forced me to do ugly patch before creating package, just to be able to use both. Additionally, I cannot really rename private Task.h header, as it has been in project for a while and people got very familiar with it. It would create a lot of confusion I think. It being a base class also doesn't help.

It is true that just removing task.h is not good at all. But, renaming the implementation file and providing new header would be great. On top of that some CMake option to enable/disable legacy header could be added to provide backwards compatibility. 
Then anyone who has this kind of conflict could just use the cmake option override to get rid of it or, if no option provided, just git patch the cmake file to remove legacy header from the library definition.

So, my proposal is:
qcoro/task.h -> qcoro/qcorotask.h
+QCoroTask
+QCoroTaskFwd
Task header added based on CMake option

**Comment by danvratil** [comment]
Renaming Task to QCoroTask + CMake option to keep/disable task.h sound good to me.

The `QCoroTaskFwd`, I guess I'm fine with having that, but I wouldn't use it in QCoro itself, since it leads to broken header, as without including `QCoroTask`, you would end up with compilation errors when `co_await`ing something from QCoro. 

On second thought, I'm about to introduce generators and I don't know whether I also want to have QCoroGeneratorFwd and QCoroAsyncGenreatorFwd. Maybe just QCoroFwd that would forward declare all the public QCoro types would be good enough. What do you think?

**Comment by jmiturasolutions** [comment]
> Renaming Task to QCoroTask + CMake option to keep/disable task.h sound good to me.

Great!

QCoroFwd sound good to me!

**Comment by danvratil** [comment]
I've merged #76 to main, which deprecates `task.h` and introduces `qcorotask.h`. You can pass `-DQCORO_DISABLE_DEPRECATED_TASK_H` to cmake when building QCoro to avoid building and installing the task.h header.
